services:
  mc-game-server:
    image: gameservermanagers/gameserver:mc
    platform: linux/amd64
    container_name: ${MCSERVER_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./volumes/mcserver:/data
    ports:
      - "${MCSERVER_PORT}:25565/tcp"
      - "${MCSERVER_PORT}:25565/udp"

  gmod-game-server:
    image: gameservermanagers/gameserver:gmod
    platform: linux/amd64
    container_name: ${GMOD_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./volumes/gmodserver:/data
    ports:
      - "${GMOD_PORT}:27015/tcp"
      - "${GMOD_PORT}:27015/udp"

  l4d2-game-server:
    image: gameservermanagers/gameserver:l4d2
    platform: linux/amd64
    container_name: ${L4D2_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./volumes/l4d2server:/data
    ports:
      - "${L4D2_PORT}:27015/tcp"
      - "${L4D2_PORT}:27015/udp"
